#pragma config(Motor,  motorA,          AxisA,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          AxisB,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          AxisC,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          AxisD,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	//init
	char demText[] = "HELLO";
	int charPointer = 0;

	float x = 	160;
	float y = 	0;
	float z = 	30;

	float angleA 	= 		-20;
	float angleBC = 		80;
	float angleD 	= 		-50;

	float angleBCnow  =		30;

	int plusMinusSpeedA 	=		5;
	int plusMinusSpeedBC 	= 	5;
	int plusMinusSpeedD 	= 	5;

	int setstart = 0;


	//init Konstanten

// DAS IST EIN TEST - AENDERUNGSKOMMENTAR

	//init temp zero Pos
	setMotorBrakeMode(AxisA,motorBrake);
	setMotorBrakeMode(AxisB,motorBrake);
	setMotorBrakeMode(AxisC,motorBrake);
	setMotorBrakeMode(AxisD,motorBrake);
	resetMotorEncoder(AxisA);
	resetMotorEncoder(AxisB);
	resetMotorEncoder(AxisC);
	resetMotorEncoder(AxisD);

	while(true)
	{
		//start button
		if(getButtonPress(buttonRight) == 1)
		{
			setstart = 1;
		}

		while(setstart == 1)
		{

			//move Axis D to save position
			setMotorTarget(motorD, -55, 5);
			waitUntilMotorStop(motorD);

			setMotorBrakeMode(AxisD,motorBrake);

			//move Axis A to zero position
			setMotorTarget(motorA, 97, 5);
			waitUntilMotorStop(motorA);

			setMotorBrakeMode(AxisA,motorBrake);

			//move Axis BC to zero position
			setMotorSyncEncoder(motorB, motorC, 0, 11, -5);
			waitUntilMotorStop(motorB);
			waitUntilMotorStop(motorC);

			setMotorBrakeMode(AxisB,motorBrake);
			setMotorBrakeMode(AxisC,motorBrake);
			delay(300);

			//Set zero Axis A and BC
			resetMotorEncoder(AxisA);
			resetMotorEncoder(AxisB);
			resetMotorEncoder(AxisC);

			//move Axis BC to wait position
			//move Axis D to zero position
			setMotorSyncEncoder(motorB, motorC, 0, 90, -5);
			setMotorTarget(motorD, 71, 6);

			waitUntilMotorStop(motorB);
			waitUntilMotorStop(motorC);
			waitUntilMotorStop(motorD);

			setMotorBrakeMode(AxisB,motorBrake);
			setMotorBrakeMode(AxisC,motorBrake);
			setMotorBrakeMode(AxisD,motorBrake);
			delay(300);

			//set zero Axis D
			resetMotorEncoder(AxisD);

			//move Axis D to wait position
			setMotorTarget(motorD, 90, 10);
			waitUntilMotorStop(motorD);

			setMotorBrakeMode(AxisD,motorBrake);



//Button coordinates

			if(demText[charPointer] == 'h')
			{
				x =	170;
				y = 0;
				z = 20;
			}

			if(demText[charPointer] == 'b')
			{
				x =	170;
				y = 0;
				z = 20;
			}

//calculations

			//calc angle Axis A


			//move direction Axis A
			if(getMotorEncoder(motorA)> angleA && plusMinusSpeedA < 0)
			{
				plusMinusSpeedA = plusMinusSpeedA*(-1);
			}
			if(getMotorEncoder(motorA)< angleA && plusMinusSpeedA > 0)
			{
				plusMinusSpeedA = plusMinusSpeedA*(-1);
			}

			//calc angle Axis BC


			//move direction Axis BC
			if(-getMotorEncoder(motorB)> angleBC && plusMinusSpeedBC < 0)
			{
				plusMinusSpeedBC = plusMinusSpeedBC*(-1);
			}
			if(-getMotorEncoder(motorB)< angleBC && plusMinusSpeedBC > 0)
			{
				plusMinusSpeedBC = plusMinusSpeedBC*(-1);
			}

			//angle absolut to incremental
			angleBCnow = getMotorEncoder(motorB)*(-1);
			angleBC = angleBC - angleBCnow;

			//calc angle Axis D


			//move direction Axis D
			if(getMotorEncoder(motorD)> angleD && plusMinusSpeedD < 0)
			{
				plusMinusSpeedD = plusMinusSpeedD*(-1);
			}
			if(getMotorEncoder(motorD)< angleD && plusMinusSpeedD > 0)
			{
				plusMinusSpeedD = plusMinusSpeedD*(-1);
			}

//Move Axis

			//move Axis A und D
			setMotorTarget(motorA, -angleA, plusMinusSpeedA);
			setMotorTarget(motorD, -angleD, plusMinusSpeedD);

			waitUntilMotorStop(motorA);
			waitUntilMotorStop(motorD);

			setMotorBrakeMode(AxisA,motorBrake);
			setMotorBrakeMode(AxisD,motorBrake);

			//move Axis BC
			setMotorSyncEncoder(motorB, motorC, 0, angleBC, plusMinusSpeedBC);

			waitUntilMotorStop(motorB);
			waitUntilMotorStop(motorC);

			setMotorBrakeMode(AxisB,motorBrake);
			setMotorBrakeMode(AxisC,motorBrake);

			//move Axis BC back to wait pos
			angleBC = 100;

			//move direction Axis BC
			if(-getMotorEncoder(motorB)> angleBC && plusMinusSpeedBC < 0)
			{
				plusMinusSpeedBC = plusMinusSpeedBC*(-1);
			}
			if(-getMotorEncoder(motorB)< angleBC && plusMinusSpeedBC > 0)
			{
				plusMinusSpeedBC = plusMinusSpeedBC*(-1);
			}

			angleBCnow = getMotorEncoder(motorB)*(-1);
			angleBC = angleBC - angleBCnow;

			setMotorSyncEncoder(motorB, motorC, 0, angleBC, plusMinusSpeedBC);

			waitUntilMotorStop(motorB);
			waitUntilMotorStop(motorC);

			setMotorBrakeMode(AxisB,motorBrake);
			setMotorBrakeMode(AxisC,motorBrake);

//Next Pointer
			charPointer = charPointer + 1;
			setstart = 0;
		}
	}
}
